### ISSUE TITLE
Consider adding a license?

### ISSUE THREAD

**Issue by bridadan** [zorxx/dfplayer#1]
I realize it may have been quite sometime since you've looked at this project, but would you consider adding a license to this project? This was exactly what I was looking for! I'm starting a project on an STM32 microcontroller and this library looks very portable!

Thanks very much, and nice work! 😄

**Comment by bridadan** [comment]
Oh gosh, totally missed the `LICENSE` file! 🤦‍♂️ Please ignore me, thanks again!

**Comment by zorxx** [comment]
Thanks for the feedback - enjoy!
